In [5]:
import numpy as np
kernel = np.ones((3, 3))
k=kernel/np.sum(kernel)
print(k)


[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [82]:
def create_kernel(dim):
    kernel = np.zeros((dim,dim))
    mitad = dim//2
    print(mitad)
    cont = 1
    for x, y in np.ndindex(kernel.shape):
        
        if x == 0 and y <= mitad:
             kernel[x,y]=cont
             cont += kernel[x,y]
             if y > 1:
                 kernel[x,y] = kernel[x,y-1]+kernel[x,0]
                 
        if x == 1 and y <= mitad:
            kernel[x,y] = kernel[x-1,y]*2
        if x > 1 and x <= mitad and y <= mitad:
            kernel[x,y] = kernel[x-1,y] + kernel[0,y]

        if y > mitad:
            kernel[x,y] = kernel[x,y-1] - kernel[x,0]

        if x > mitad:
            kernel[x,y] = kernel[x-1,y] - kernel[0,y]

    print(kernel)


In [95]:
def create_kernel2(dim):
    kernel = np.zeros((dim, dim))
    mid = dim // 2

    for x in range(mid + 1):
        for y in range(mid + 1):
            if x == 0 and y == 0:
                kernel[x, y] = 1
            else:
                kernel[x, y] = kernel[x - 1, y] + kernel[x, y - 1]

    # Copiar la mitad superior izquierda al cuadrante superior derecho
    #kernel[:mid + 1, mid + 1:] = kernel[:mid + 1, :mid]

    # Copiar el cuadrante superior izquierdo al cuadrante inferior izquierdo
    #kernel[mid + 1:, :mid + 1] = kernel[:mid + 1, :mid]

    # Espejo verticalmente para obtener la mitad inferior
    #kernel[mid + 1:, :] = np.flip(kernel[:mid + 1, :], axis=0)

    return kernel

# Ejemplo de uso:
dim = 5
kernel = create_kernel2(dim)
print(kernel)

[[1. 1. 1. 0. 0.]
 [1. 2. 3. 0. 0.]
 [1. 3. 6. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [86]:
create_kernel(9)

4
[[ 1.  2.  3.  4.  5.  4.  3.  2.  1.]
 [ 2.  4.  6.  8. 10.  8.  6.  4.  2.]
 [ 3.  6.  9. 12. 15. 12.  9.  6.  3.]
 [ 4.  8. 12. 16. 20. 16. 12.  8.  4.]
 [ 5. 10. 15. 20. 25. 20. 15. 10.  5.]
 [ 4.  8. 12. 16. 20. 16. 12.  8.  4.]
 [ 3.  6.  9. 12. 15. 12.  9.  6.  3.]
 [ 2.  4.  6.  8. 10.  8.  6.  4.  2.]
 [ 1.  2.  3.  4.  5.  4.  3.  2.  1.]]


In [1]:
import numpy as np
def bartlett_kernel(size):
    if size % 2 == 0:
        raise ValueError("El tamaño del kernel debe ser impar.")

    kernel = np.zeros((size,size))
    mid = size // 2    

    for x,y in np.ndindex((mid+1,mid+1)):
        kernel[x,y]=(y+1)*(x+1)
                
    kernel[:mid+1,mid+1:] = np.flip(kernel[:mid+1,:mid],axis=1) 
    kernel[mid+1:,:] = np.flip(kernel[:mid,:],axis=0)      
            
    return kernel
        

In [2]:
bartlett = bartlett_kernel(3)
print(bartlett)

[[1. 2. 1.]
 [2. 4. 2.]
 [1. 2. 1.]]


In [70]:
def gaussiano_kernel(dim):
    if dim <= 0:
        raise ValueError("La dimensión debe ser mayor que 0")
    
    ar=np.array([1])
    
    while len(ar) < dim:
        f = np.ones(len(ar) + 1)
        f[1:-1] = ar[:-1]+ar[1:]
        ar = f
    
    return ar.reshape(-1, 1) * ar

In [72]:
gausiano = gaussiano_kernel(5)
print(gausiano)

[[ 1.  4.  6.  4.  1.]
 [ 4. 16. 24. 16.  4.]
 [ 6. 24. 36. 24.  6.]
 [ 4. 16. 24. 16.  4.]
 [ 1.  4.  6.  4.  1.]]


In [80]:
def laplaciano_kernel(v):
    kernel = None
    if v==4:
        kernel = np.zeros((3,3))
        kernel[1,:] = -1
        kernel[:,1] = -1
        kernel[1,1] = 4
    if v==8:
        kernel = np.ones((3,3))*(-1)
        kernel[1,1] = 8
    return kernel

In [82]:
laplaciano = laplaciano_kernel(8)
print(laplaciano)

[[-1. -1. -1.]
 [-1.  8. -1.]
 [-1. -1. -1.]]


In [91]:
def sobel_kernel(orientacion):
    f = np.array([1, 2, 1])
    kernel = np.zeros((3, 3))
    f_flat = f.flatten()  # Convertmos 'f' en un array unidimensional
    
    if orientacion == 'Oeste':
        kernel[:, 0] = f_flat * (-1)
        kernel[:, 2] = f_flat
    elif orientacion == 'Este':
        kernel[:, 0] = f_flat
        kernel[:, 2] = f_flat * (-1)
    elif orientacion == 'Norte':
        kernel[0, :] = f_flat * (-1)
        kernel[2, :] = f_flat
    else:
        kernel[0, :] = f_flat
        kernel[2, :] = f_flat * (-1)
    
    return kernel

In [94]:
sobel = sobel_kernel('Norte')
print(sobel)

[[-1. -2. -1.]
 [ 0.  0.  0.]
 [ 1.  2.  1.]]


In [88]:
f = np.array([1,2,1])
print((f.reshape(-1, 1)*(-1)).shape)
print(laplaciano[:,0].shape)

(3, 1)
(3,)


In [5]:
def _convolution1(image, kernel = np.ones((1,1))):
    convolved = np.zeros((np.array(image.shape)-np.array(kernel.shape)+1))
    print(convolved)
    for x in range(convolved.shape[0]):
        for y in range(convolved.shape[1]):
            convolved[x,y] = (image[x:x+kernel.shape[0],y:y+kernel.shape[1]]*kernel).sum()
    return convolved

In [3]:
def _convolution2(image, kernel = np.ones((1,1))):
    convolved = np.zeros((np.array(image.shape)-np.array(kernel.shape)+1))
    for x, y in np.ndindex(convolved.shape):
        convolved[x,y] = (image[x:x+kernel.shape[0],y:y+kernel.shape[1]]*kernel).sum()
    return convolved

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import imageio

# Cargar la imagen y el kernel
im = np.clip(imageio.imread('Charly.bmp') / 255.0, 0.0, 1.0)
print(im[:,:,1].shape)
print(k.shape)
im2=_convolution1(im,k)
plt.imshow(im2)
plt.show()

(288, 282)
(3, 3)


C:\Users\Luciano-PC\AppData\Local\Temp\ipykernel_9644\843149348.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  im = np.clip(imageio.imread('Charly.bmp') / 255.0, 0.0, 1.0)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import imageio

# Cargar la imagen y el kernel
im = np.clip(imageio.imread('Charly.bmp') / 255.0, 0.0, 1.0)
k = kernel / np.sum(kernel)

# Verificar las dimensiones de la imagen y el kernel
if im.shape[0] < k.shape[0] or im.shape[1] < k.shape[1]:
    raise ValueError("El kernel es más grande que la imagen. Ajusta el tamaño del kernel o la imagen.")

# Calcular las dimensiones de relleno
padding_x = k.shape[0] - 1
padding_y = k.shape[1] - 1

# Rellenar la imagen de manera simétrica para que la forma sea válida
im_padded = np.pad(im, ((padding_x, padding_x), (padding_y, padding_y)), mode='symmetric')

# Realizar la convolución con la imagen rellenada
result = _convolution1(im_padded, k)

# Mostrar el resultado
plt.imshow(result, cmap='gray')
plt.show()



C:\Users\Margarita Zerpa\AppData\Local\Temp\ipykernel_8620\3386615298.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  im = np.clip(imageio.imread('Charly.bmp') / 255.0, 0.0, 1.0)


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2)  and requested shape (3,2)